name: Docker Image CI for svc base

on:
  schedule:
    - cron: "0 0 1 * *"

env:
  IMG: bxwill/qsphere
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  TAG_PREFIX: svc
  CODE_ROOT: svc

jobs:

  scheduleBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for service base image
       run : |
         cd ./${CODE_ROOT}
         docker build . --file Dockerfile-svc-base --tag ${IMG}:svc-base
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
         docker push ${IMG}:svc-base